POST http://localhost:3003/class
Content-Type: application/json

    {
        "name": "Shaw",
        "module": 5
    }
    
###   

POST http://localhost:3003/teacher
Content-Type: application/json

    {
        "name": "Murillo",
        "email": "Murilao@Labenu.com",
        "birthDate": "2000-06-23",
        "classID": 1,
        "specs": "JS"
    }

###

GET http://localhost:3003/class

###

PATCH http://localhost:3003/class/2?module=4