POST http://localhost:3003/class
Content-Type: application/json

    {
        "name": "Shaw",
        "module": 5
    }
    
###   

POST http://localhost:3003/teacher
Content-Type: application/json

    {
        "name": "Janna",
        "email": "confusiCode@Labenu.com",
        "birthDate": "23/12/1997",
        "classID": 1,
        "specs": ["React","JS","Typescript"]
    }

###

POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Charles",
    "email": "charles@email.com",
    "birthDate": "03/01/1995",
    "classID": 1,
    "hobby": ["Jogar bola", "Jogar bola de novo"]
}

###

GET http://localhost:3003/class

###

GET http://localhost:3003/student?nome=luiao

###

GET http://localhost:3003/teacher

###

PATCH http://localhost:3003/class/2?module=4

###

PATCH http://localhost:3003/teacher/1?class=1

###

PATCH  http://localhost:3003/student/1?class=2

